namespace AlienFX
{
    namespace Dialogs
    {
        [default_interface]
        runtimeclass WhiteBalanceDialog : Microsoft.UI.Xaml.Controls.ContentDialog
        {
            WhiteBalanceDialog();
        }
    }
}
