namespace AlienFX
{
    namespace Controls
    {
        [default_interface]
        runtimeclass FreqBarsControl : Microsoft.UI.Xaml.Controls.UserControl
        {
            FreqBarsControl();
        }
    }
}
