namespace AlienFX
{
    namespace Controls
    {
        [default_interface]
        runtimeclass GaugeControl : Microsoft.UI.Xaml.Controls.UserControl
        {
            GaugeControl();
        }
    }
}
