namespace AlienFX
{
    namespace Controls
    {
        [default_interface]
        runtimeclass LedGridControl : Microsoft.UI.Xaml.Controls.UserControl
        {
            LedGridControl();
        }
    }
}
